[[main]]
none = "none"

[[main]]
name = "blogs"
pageRef = "blogs"
identifier = "2ER1laWJ6X"
weight = 3

[[main]]
name = "projects"
pre = "github"
pageRef = "projects"
identifier = "YdE5rYjb5I"
weight = 2

[[footer]]
none = "none"
